airlines/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("flight/", include("flight.urls")),
]

flight/urls.py
from django.urls import path
from .views import index, add_flight, delete_flight, update_flight

app_name = "flight"
urlpatterns = [
    path("", index, name="index"),
    path("add_flight/", add_flight, name="add_flight"),
    path("delete_flight/<int:id>/", delete_flight, name="delete_flight"),
    path("update_flight/<int:id>/", update_flight, name="update_flight"),
]

flight/models.py
from django.db import models

# Create your models here.
class Airport(models.Model):
    city = models.CharField(max_length=64)
    code = models.CharField(max_length=3)
    
    def __str__(self):
        return str(self.city)
    
    
class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="destinations")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

class Passenger(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    flight = models.ManyToManyField(Flight, related_name="passengers")

flight/forms.py
from django import forms
from .models import Flight

class FlightForm(forms.ModelForm):
    class Meta:
        model = Flight
        fields = "__all__"

flight/views.py
from django.shortcuts import render
from .models import Flight
from .forms import FlightForm
from django.urls import reverse
from django.http import HttpResponseRedirect

# Create your views here.
def index(request):
    flights = Flight.objects.all()
    form = FlightForm()
    return render(request, "flight/index.html", {
        "flights" : flights,
        "forms":form,
    })
    
def add_flight(request):
    form = FlightForm(request.POST)
    if form.is_valid():
        form.save()
    
    return HttpResponseRedirect(reverse("flight:index"))

def delete_flight(request, id):
    flight = Flight.objects.get(id=id)
    flight.delete()
    return HttpResponseRedirect(reverse("flight:index"))

def update_flight(request, id):
    flight = Flight.objects.get(id=id)
    form = FlightForm(request.POST or None, instance=flight)
    
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("flight:index"))
        
    return render(request,"flight/update_view.html",{
        "forms":form,
        "pk": id
    })

flight/templates/flight/index.html
{% extends "flight/layout.html" %} {% block title %} Flights {% endblock %}
{%block body %}

<h1>List of Flights</h1>

<ul>
  {% for flight in flights %}
  <a href="{% url 'flight:delete_flight' flight.id %}">Delete</a>
  <a href="{% url 'flight:update_flight' flight.id %}">Edit</a>
  <li>
    Origin: {{flight.origin}} - Destination: {{flight.destination}} :
    {{flight.duration}} mins
  </li>
  {% endfor %}
</ul>

<div>
  <form action="{% url 'flight:add_flight' %}" method="post">
    {% csrf_token %} {{forms.as_p}}
    <input type="submit" value="Add Flight" />
  </form>
</div>

{% endblock %}

flight/templates/flight/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<body>
    {% block body %}

    {% endblock %}
</body>

</html>

flight/templates/flight/update_view.html
{% extends "flight/layout.html" %} {% block title %} Update Flight {% endblock
%} {%block body %}
<h1>Update Flight</h1>
<form action="{% url 'flight:update_flight' pk %}" method="post">
  {% csrf_token %} {{forms.as_p}}
  <input type="submit" value="Update Flight" />
</form>
{%endblock%}